# Generated by Django 5.0.2 on 2024-02-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
