# Generated by Django 5.0 on 2023-12-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_categorymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='last_modified_date',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(max_length=100, verbose_name='категория'),
        ),
    ]
