# Generated by Django 5.0 on 2024-01-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_created_at_productmodel_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='Product',
        ),
    ]
