# Generated by Django 5.0 on 2024-01-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_blogpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='views_number',
            new_name='views_count',
        ),
    ]
