# Generated by Django 5.0 on 2024-01-23 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.AddField(
            model_name='client',
            name='comment',
            field=models.TextField(null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='client',
            name='post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.post', verbose_name='post id'),
        ),
        migrations.AlterField(
            model_name='client',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.product', verbose_name='product id'),
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.TimeField(verbose_name='Mailing time')),
                ('frequency', models.CharField(choices=[('daily', 'Once a day'), ('weekly', 'Once a week'), ('monthly', 'Once a month')], max_length=7, verbose_name='Frequency')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('created', 'Created'), ('started', 'Started')], default='created', max_length=10, verbose_name='Mailing status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='main_app.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Mailing',
                'verbose_name_plural': 'Mailings',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of last attempt')),
                ('attempt_status', models.CharField(max_length=15, verbose_name='Attempt status')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='Mail server response, if any')),
                ('mailing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main_app.mailing', verbose_name='Mailing')),
            ],
            options={
                'verbose_name': 'Mailing Log',
                'verbose_name_plural': 'Mailing Logs',
            },
        ),
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Letter subject')),
                ('body', models.TextField(verbose_name='Body of the letter')),
                ('mailing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main_app.mailing', verbose_name='Mailing')),
            ],
            options={
                'verbose_name': 'Mailing Message',
                'verbose_name_plural': 'Mailing Messages',
            },
        ),
    ]
