# Generated by Django 5.0 on 2024-01-24 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_email_client_contact_email_client_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name',), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailinglog',
            options={'verbose_name': 'Журнал рассылки', 'verbose_name_plural': 'Журналы рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailingmessage',
            options={'verbose_name': 'Сообщение рассылки', 'verbose_name_plural': 'Сообщения рассылки'},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='mailinglog',
            old_name='mailing_id',
            new_name='mailing',
        ),
        migrations.RenameField(
            model_name='mailingmessage',
            old_name='mailing_id',
            new_name='mailing',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='mailing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='main_app.mailing', verbose_name='Mailing'),
            preserve_default=False,
        ),
    ]
