# Generated by Django 5.0 on 2024-01-24 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_client_options_alter_mailing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='main_app.mailing', verbose_name='Mailing'),
        ),
    ]
