# Generated by Django 5.0 on 2024-01-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_mailingmessage_mailing_mailing_mailing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingmessage',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Отправка'),
        ),
    ]
