# Generated by Django 5.0 on 2024-01-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_mailingmessage_sent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingMessage',
            new_name='Message',
        ),
    ]
