# Generated by Django 5.0 on 2024-02-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_product_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglog',
            name='mailing',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mailing',
        ),
        migrations.DeleteModel(
            name='Mailing',
        ),
        migrations.DeleteModel(
            name='MailingLog',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
