# Generated by Django 5.0 on 2024-02-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_remove_productversion_current_version_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
