# Generated by Django 5.0.2 on 2024-03-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='user_email',
            field=models.EmailField(default='chernyshova0508@gmail.com', max_length=254),
        ),
    ]
