# Generated by Django 5.0.2 on 2024-03-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_remove_product_user_product_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
